### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by UnknownUser647254925487** [UnknownUser647254925487/Berufsschule_CarSensor#3]
-StreamWriter im richtigen Ordner- SOLVED
-Tabelle mit Inhalt füllen -SOLVED
  ->neue Klasse? -Class created, not Working -SOLVED
-Tabelle mit buntem Hintergrund (rot/grün) -SOLVED
-Text-Datei muss vor Programmstart existieren -SOLVED

Bei Bedarf:
-Auswertung der Messdaten (Diagramme)

**Comment by Blue-Code252** [comment]
Warum auch nicht ^^

**Comment by UnknownUser647254925487** [comment]
Done Biadsch
